services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Add this line to load the .env file
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
