version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rainsafe-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - MONGO_URL=mongodb://mongo:27017/rainsafe_db
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: rainsafe-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=rainsafe_db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:1.72.1
    container_name: rainsafe-n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
      - TZ=UTC
    volumes:
      - n8n-data:/home/node/.n8n
    depends_on:
      - backend
      - mongo
    restart: unless-stopped

volumes:
  mongo-data:
  n8n-data:
